### ISSUE TITLE
Incorrect bundle configuration documentation

### ISSUE THREAD

**Issue by wesnick** [gbprod/elastica-bundle#18]
The installation docs indicate "elastica_bundle" key for bundle configuration.

Using this key results in an error
```
 [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException] 
There is no extension able to load the configuration for "elastica_bundle"
```
I am using
versions : * v3.2.6

Changing the key to "elastica" resolves this issue.

**Comment by gbprod** [comment]
That's right !
Thank you !
