### ISSUE TITLE
Web toolbar widget integration is broken in recent versions of Symfony

### ISSUE THREAD

**Issue by FlyingDR** [gbprod/elastica-bundle#22]
In recent versions of Symfony colon-based format of Twig template references was [deprecated](https://symfony.com/doc/3.4/templating/namespaced_paths.html). However current version of the bundle uses old syntax ([1](https://github.com/gbprod/elastica-bundle/blob/v1.1.0/src/ElasticaBundle/Resources/config/services.yml#L5), [2](https://github.com/gbprod/elastica-bundle/blob/v1.1.0/src/ElasticaBundle/Resources/views/Collector/elastica.html.twig#L1), [3](https://github.com/gbprod/elastica-bundle/blob/v1.1.0/src/ElasticaBundle/Resources/views/Collector/elastica.html.twig#L35)) and it breaks web toolbar on e.g. Symfony 3.4

**Comment by gbprod** [comment]
Closed by #23 
Thanks @FlyingDR
